Laravel 11.x Compatibility
Flowframe/laravel-trend pull request #53
Opened 2024-02-27 18:32 UTC by laravel-shift

This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

2024-02-27 18:32 UTC, laravel-shift commented
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/Flowframe/laravel-trend/pull/53/commits/d2b0ce64a7916ddd97b612af42664e25975944aa?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

2024-02-27 18:32 UTC, laravel-shift commented
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-trend.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "flowframe/laravel-trend": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

2024-03-11 15:57 UTC, lloricode requested changes
please add php8.3, thank you

2024-03-11 15:57 UTC, lloricode commented on .github/workflows/run-tests.yml
> +        php: [8.0, 8.1, '8.2']
please add php8.3, thank you

2024-03-12 18:01 UTC, ahinkle commented
ping @Larsklopstra ❤️

2024-03-13 09:53 UTC, niclas-timm commented
@Larsklopstra would be great to get this PR merged! Let me know if you need hep with anything.

2024-03-14 13:35 UTC, ConnorHowell commented
Why not remove `illuminate/contracts` entirely? It's not used as far as I can tell (unless I'm missing something obvious?).

2024-03-14 13:43 UTC, merged